#!/usr/bin/env python3
"""Unity-aligned recurrent foraging training and checkpoint pipeline.

The policy has eight directional actions and eight normalized floating-point
ray distances. It trains on procedural pockets, L-walls, offset barriers, and
variable U-traps. C-shapes and zigzag gates are generated by the same simulator
but strictly withheld until final zero-shot evaluation.

Curiosity uses forward-ensemble disagreement as a practical epistemic
uncertainty proxy. It is not an exact Bayesian information-gain calculation.
"""

import json
import math
from collections import Counter, deque
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from tiny_lab import OUT, set_seed


SIZE = 15
MAX_STEPS = 96
RAY_RANGE = 6.0
RAY_STEP = 0.20
FOOD_SIGHT = 7.0
MOVES = np.asarray(
    [[0, 1], [1, 1], [1, 0], [1, -1], [0, -1], [-1, -1], [-1, 0], [-1, 1]],
    dtype=np.int64,
)
ACTION_NAMES = ["up", "up_right", "right", "down_right", "down", "down_left", "left", "up_left"]
CORE_DIM = 8 + 1 + 2 + 1
OBS_DIM = CORE_DIM + len(MOVES) + 1
TRAIN_FAMILIES = ["open", "pocket", "l_wall", "offset_barriers", "u_trap"]
WITHHELD_FAMILIES = ["c_shape", "zigzag_gate"]
CURIOSTY_SWEEP = [0.012, 0.018, 0.024]
TRAIN_SEEDS = [101, 211, 307, 419, 523]
CHECKPOINT_DIR = Path("checkpoints/upgraded_foraging")


def rectangle(x0, y0, width, height):
    return {(x, y) for x in range(x0, x0 + width) for y in range(y0, y0 + height)}


def rotate_cell(cell, turns):
    x, y = cell
    for _ in range(turns % 4):
        x, y = SIZE - 1 - y, x
    return x, y


def rotate_layout(blocked, start, food, turns):
    return (
        {rotate_cell(cell, turns) for cell in blocked},
        rotate_cell(start, turns),
        rotate_cell(food, turns),
    )


def reachable(blocked, start, goal):
    queue = deque([start])
    seen = {start}
    while queue:
        cell = queue.popleft()
        if cell == goal:
            return True
        for move in MOVES:
            nxt = cell[0] + int(move[0]), cell[1] + int(move[1])
            if not (0 <= nxt[0] < SIZE and 0 <= nxt[1] < SIZE):
                continue
            if nxt in blocked or nxt in seen:
                continue
            if move[0] != 0 and move[1] != 0:
                side_a = cell[0] + int(move[0]), cell[1]
                side_b = cell[0], cell[1] + int(move[1])
                if side_a in blocked and side_b in blocked:
                    continue
            seen.add(nxt)
            queue.append(nxt)
    return False


def generate_layout(family, layout_seed):
    rng = np.random.default_rng(layout_seed)
    blocked = set()
    start = (SIZE // 2, 2)
    food = (SIZE // 2, SIZE - 3)

    if family == "pocket":
        width = int(rng.integers(4, 8))
        depth = int(rng.integers(3, 7))
        left = (SIZE - width) // 2
        bottom = int(rng.integers(4, 7))
        blocked |= rectangle(left, bottom, 1, depth)
        blocked |= rectangle(left + width - 1, bottom, 1, depth)
        blocked |= rectangle(left, bottom + depth - 1, width, 1)
        start = (SIZE // 2, bottom + 1)
        food = (SIZE // 2, min(SIZE - 2, bottom + depth + 2))
    elif family == "open":
        start = (int(rng.integers(2, 6)), int(rng.integers(2, 6)))
        food_candidates = [
            (x, y)
            for x in range(1, SIZE - 1)
            for y in range(1, SIZE - 1)
            if 4.0 <= math.dist(start, (x, y)) <= 6.5
        ]
        food = food_candidates[int(rng.integers(len(food_candidates)))]
        for _ in range(int(rng.integers(0, 5))):
            blocked.add(tuple(rng.integers(2, SIZE - 2, size=2)))
    elif family == "l_wall":
        x = int(rng.integers(4, 9))
        y = int(rng.integers(4, 8))
        vertical = int(rng.integers(4, 8))
        horizontal = int(rng.integers(3, 7))
        blocked |= rectangle(x, y, 1, vertical)
        blocked |= rectangle(x, y + vertical - 1, horizontal, 1)
        start = (max(1, x - 2), max(1, y - 2))
        food = (min(SIZE - 2, x + horizontal + 1), min(SIZE - 2, y + vertical + 1))
    elif family == "offset_barriers":
        gap_a = int(rng.integers(2, 6))
        gap_b = int(rng.integers(8, 13))
        blocked |= rectangle(4, 1, 1, SIZE - 3)
        blocked |= rectangle(10, 2, 1, SIZE - 3)
        blocked.discard((4, gap_a))
        blocked.discard((10, gap_b))
        start = (2, 2)
        food = (12, 12)
    elif family == "u_trap":
        width = int(rng.integers(4, 8))
        depth = int(rng.integers(4, 8))
        left = (SIZE - width) // 2
        bottom = int(rng.integers(3, 6))
        blocked |= rectangle(left, bottom, 1, depth)
        blocked |= rectangle(left + width - 1, bottom, 1, depth)
        blocked |= rectangle(left, bottom + depth - 1, width, 1)
        start = (SIZE // 2, bottom + 1)
        food = (SIZE // 2, min(SIZE - 2, bottom + depth + 2))
    elif family == "c_shape":
        width = int(rng.integers(6, 9))
        depth = int(rng.integers(6, 9))
        left = (SIZE - width) // 2
        bottom = (SIZE - depth) // 2
        blocked |= rectangle(left, bottom, width, 1)
        blocked |= rectangle(left, bottom + depth - 1, width, 1)
        blocked |= rectangle(left, bottom, 1, depth)
        start = (left + 2, bottom + depth // 2)
        food = (min(SIZE - 2, left + width + 2), bottom + depth // 2)
    elif family == "zigzag_gate":
        blocked |= rectangle(3, 1, 1, 11)
        blocked |= rectangle(7, 3, 1, 11)
        blocked |= rectangle(11, 1, 1, 11)
        blocked.discard((3, int(rng.integers(8, 12))))
        blocked.discard((7, int(rng.integers(3, 7))))
        blocked.discard((11, int(rng.integers(8, 12))))
        start = (1, 2)
        food = (13, 12)
    else:
        raise ValueError(family)

    turns = int(rng.integers(0, 4))
    blocked, start, food = rotate_layout(blocked, start, food, turns)
    blocked.discard(start)
    blocked.discard(food)
    if not reachable(blocked, start, food):
        raise RuntimeError(f"unreachable generated layout: {family}:{layout_seed}")
    return blocked, start, food


def line_of_sight(start, goal, blocked):
    samples = max(2, int(math.ceil(math.dist(start, goal) * 5)))
    for alpha in np.linspace(0.0, 1.0, samples)[1:-1]:
        point = (int(round(start[0] + alpha * (goal[0] - start[0]))), int(round(start[1] + alpha * (goal[1] - start[1]))))
        if point in blocked:
            return False
    return True


@dataclass
class StepResult:
    obs: np.ndarray
    reward: float
    done: bool
    ate: bool
    collision: bool


class ContinuousRayForagingWorld:
    def __init__(self, family, layout_seed, food_reward=2.0):
        self.family = family
        self.layout_seed = int(layout_seed)
        self.food_reward = float(food_reward)
        self.blocked, self.start, self.food = generate_layout(family, layout_seed)
        self.reset()

    def reset(self):
        self.pos = self.start
        self.steps = 0
        self.hunger = 0.12
        self.last_action = 0
        self.last_reward = 0.0
        self.visits = {self.pos: 1}
        return self.observe()

    def is_blocked(self, cell):
        return not (0 <= cell[0] < SIZE and 0 <= cell[1] < SIZE) or cell in self.blocked

    def ray_distance(self, move):
        direction = move.astype(np.float32)
        direction /= np.linalg.norm(direction)
        origin = np.asarray(self.pos, dtype=np.float32) + 0.5
        for distance in np.arange(RAY_STEP, RAY_RANGE + RAY_STEP, RAY_STEP):
            point = origin + direction * distance
            cell = int(math.floor(point[0])), int(math.floor(point[1]))
            if self.is_blocked(cell):
                return float(np.clip((distance - RAY_STEP) / RAY_RANGE, 0.0, 1.0))
        return 1.0

    def food_visible(self):
        return math.dist(self.pos, self.food) <= FOOD_SIGHT and line_of_sight(self.pos, self.food, self.blocked)

    def observe(self):
        rays = np.asarray([self.ray_distance(move) for move in MOVES], dtype=np.float32)
        visible = self.food_visible()
        food_delta = (np.asarray(self.food) - np.asarray(self.pos)) / (SIZE - 1) if visible else np.zeros(2)
        previous_action = np.zeros(len(MOVES), dtype=np.float32)
        previous_action[self.last_action] = 1.0
        return np.concatenate(
            [rays, [float(visible)], food_delta, [self.hunger], previous_action, [self.last_reward]]
        ).astype(np.float32)

    def step(self, action):
        action = int(action)
        self.last_action = action
        move = MOVES[action]
        candidate = self.pos[0] + int(move[0]), self.pos[1] + int(move[1])
        collision = self.is_blocked(candidate)
        if not collision and move[0] != 0 and move[1] != 0:
            side_a = self.pos[0] + int(move[0]), self.pos[1]
            side_b = self.pos[0], self.pos[1] + int(move[1])
            collision = side_a in self.blocked and side_b in self.blocked
        old_distance = math.dist(self.pos, self.food)
        if not collision:
            self.pos = candidate
        self.visits[self.pos] = self.visits.get(self.pos, 0) + 1
        new_distance = math.dist(self.pos, self.food)

        self.steps += 1
        self.hunger = min(1.0, self.hunger + 1.0 / MAX_STEPS)
        ate = self.pos == self.food
        visible_progress = 0.0
        if self.food_reward > 0.0 and self.food_visible() and not collision:
            visible_progress = 0.040 * (old_distance - new_distance)
        reward = self.food_reward if ate and self.food_reward > 0.0 else -0.007 - 0.006 * self.hunger + visible_progress
        if collision:
            reward -= 0.05
        done = (ate and self.food_reward > 0.0) or self.steps >= MAX_STEPS
        if self.steps >= MAX_STEPS and not (ate and self.food_reward > 0.0):
            reward -= 0.35
        self.last_reward = reward
        return StepResult(self.observe(), reward, done, ate, collision)

    def episodic_novelty(self):
        return 1.0 / math.sqrt(max(1, self.visits.get(self.pos, 1)))


class RecurrentForagingPolicy(nn.Module):
    def __init__(self, hidden_dim=64, ensemble_size=3):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.ensemble_size = ensemble_size
        self.encoder = nn.Sequential(nn.Linear(OBS_DIM, hidden_dim), nn.Tanh())
        self.memory = nn.GRUCell(hidden_dim, hidden_dim)
        self.actor = nn.Linear(hidden_dim, len(MOVES))
        self.critic = nn.Linear(hidden_dim, 1)
        self.forward_heads = nn.ModuleList(
            [
                nn.Sequential(
                    nn.Linear(hidden_dim + len(MOVES), hidden_dim),
                    nn.Tanh(),
                    nn.Linear(hidden_dim, CORE_DIM),
                )
                for _ in range(ensemble_size)
            ]
        )

    def initial_state(self, batch):
        return torch.zeros(batch, self.hidden_dim)

    def step(self, obs, hidden):
        encoded = self.encoder(obs)
        next_hidden = self.memory(encoded, hidden)
        return self.actor(next_hidden), self.critic(next_hidden).squeeze(-1), next_hidden

    def predict_core(self, hidden, action):
        one_hot = F.one_hot(action.long(), len(MOVES)).float()
        features = torch.cat([hidden, one_hot], dim=-1)
        return torch.stack([head(features) for head in self.forward_heads], dim=0)


def safety_mask_logits(logits, obs):
    required_clearance = torch.tensor(
        [0.75 * float(np.linalg.norm(move)) / RAY_RANGE for move in MOVES],
        dtype=obs.dtype,
        device=obs.device,
    )
    blocked = obs[:, : len(MOVES)] < required_clearance.unsqueeze(0)
    all_blocked = torch.all(blocked, dim=-1, keepdim=True)
    blocked = blocked & ~all_blocked
    return logits.masked_fill(blocked, -1e9)


class FailureReplay:
    def __init__(self):
        self.failures = Counter()

    def record(self, family, layout_seed, success):
        key = (family, int(layout_seed))
        if success:
            self.failures[key] = max(0, self.failures[key] - 1)
        else:
            self.failures[key] += 1

    def sample(self, rng):
        candidates = [(key, count) for key, count in self.failures.items() if count > 0]
        if not candidates:
            return None
        keys = [item[0] for item in candidates]
        weights = np.asarray([item[1] for item in candidates], dtype=np.float64)
        weights /= weights.sum()
        return keys[int(rng.choice(len(keys), p=weights))]


def new_training_world(rng, replay, food_reward=2.0, allowed_families=None, replay_probability=0.35):
    allowed_families = TRAIN_FAMILIES if allowed_families is None else allowed_families
    replay_choice = replay.sample(rng) if rng.random() < replay_probability else None
    if replay_choice is not None and replay_choice[0] not in allowed_families:
        replay_choice = None
    if replay_choice is None:
        family = allowed_families[int(rng.integers(len(allowed_families)))]
        layout_seed = int(rng.integers(1, 10_000_000))
    else:
        family, layout_seed = replay_choice
    return ContinuousRayForagingWorld(family, layout_seed, food_reward=food_reward)


def curriculum_families(update):
    if update < 80:
        return ["open"]
    if update < 180:
        return ["open", "l_wall"]
    if update < 280:
        return ["open", "l_wall", "offset_barriers"]
    return ["pocket", "l_wall", "offset_barriers", "u_trap"]


def train_policy(seed, curiosity_beta, food_reward=2.0, updates=600, env_count=20, rollout=24):
    torch.manual_seed(seed)
    rng = np.random.default_rng(seed)
    policy = RecurrentForagingPolicy()
    optimizer = torch.optim.Adam(policy.parameters(), lr=0.0016)
    replay = FailureReplay()
    envs = [
        new_training_world(
            rng,
            replay,
            food_reward=food_reward,
            allowed_families=curriculum_families(0),
            replay_probability=0.0,
        )
        for _ in range(env_count)
    ]
    obs = torch.tensor(np.stack([env.reset() for env in envs]))
    hidden = policy.initial_state(env_count)
    recent_success = deque(maxlen=200)
    curves = {"success": [], "loss": [], "replay_items": []}

    for update in range(updates):
        log_probs = []
        values = []
        rewards = []
        entropies = []
        masks = []
        predictions = []
        prediction_targets = []

        for _ in range(rollout):
            logits, value, hidden = policy.step(obs, hidden)
            logits = safety_mask_logits(logits, obs)
            dist = torch.distributions.Categorical(logits=logits)
            action = dist.sample()
            ensemble_prediction = policy.predict_core(hidden, action)
            with torch.no_grad():
                disagreement = torch.mean(torch.var(ensemble_prediction, dim=0), dim=-1)

            next_obs = []
            step_reward = []
            alive = []
            for index, env in enumerate(envs):
                result = env.step(int(action[index]))
                ensemble_uncertainty = min(2.0, float(disagreement[index]) * 80.0)
                episodic_novelty = env.episodic_novelty()
                intrinsic = curiosity_beta * (0.55 * ensemble_uncertainty + 0.45 * episodic_novelty)
                step_reward.append(result.reward + intrinsic)
                if result.done:
                    success = bool(result.ate and env.food_reward > 0.0)
                    replay.record(env.family, env.layout_seed, success)
                    recent_success.append(float(success))
                    envs[index] = new_training_world(
                        rng,
                        replay,
                        food_reward=food_reward,
                        allowed_families=curriculum_families(update),
                        replay_probability=0.0 if update < 180 else 0.35,
                    )
                    next_obs.append(envs[index].reset())
                    alive.append(0.0)
                else:
                    next_obs.append(result.obs)
                    alive.append(1.0)

            next_obs_tensor = torch.tensor(np.stack(next_obs))
            log_probs.append(dist.log_prob(action))
            values.append(value)
            rewards.append(torch.tensor(step_reward, dtype=torch.float32))
            entropies.append(dist.entropy())
            masks.append(torch.tensor(alive, dtype=torch.float32))
            predictions.append(ensemble_prediction)
            prediction_targets.append(next_obs_tensor[:, :CORE_DIM])
            obs = next_obs_tensor
            hidden = hidden * masks[-1].unsqueeze(-1)

        with torch.no_grad():
            _, bootstrap, _ = policy.step(obs, hidden)
        returns = []
        running = bootstrap
        for reward, mask in zip(reversed(rewards), reversed(masks)):
            running = reward + 0.97 * running * mask
            returns.append(running)
        returns.reverse()
        returns_t = torch.stack(returns)
        values_t = torch.stack(values)
        advantage = returns_t - values_t
        actor_loss = -(torch.stack(log_probs) * advantage.detach()).mean()
        critic_loss = 0.45 * advantage.pow(2).mean()
        entropy_loss = -0.018 * torch.stack(entropies).mean()
        aux_loss = torch.stack(
            [F.mse_loss(prediction, target.unsqueeze(0).expand_as(prediction)) for prediction, target in zip(predictions, prediction_targets)]
        ).mean()
        loss = actor_loss + critic_loss + entropy_loss + 0.18 * aux_loss
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(policy.parameters(), 0.9)
        optimizer.step()
        hidden = hidden.detach()

        curves["success"].append(float(np.mean(recent_success)) if recent_success else 0.0)
        curves["loss"].append(float(loss.detach()))
        curves["replay_items"].append(sum(1 for count in replay.failures.values() if count > 0))

    return policy.eval(), curves


def evaluate_policy(policy, families, episodes_per_family=30, seed=50_000, reset_memory=False):
    rows = []
    for family_index, family in enumerate(families):
        for episode in range(episodes_per_family):
            env = ContinuousRayForagingWorld(family, seed + family_index * 10_000 + episode)
            obs = torch.tensor(env.reset()).unsqueeze(0)
            hidden = policy.initial_state(1)
            collisions = 0
            for step in range(MAX_STEPS):
                with torch.no_grad():
                    logits, _, hidden = policy.step(obs, hidden)
                    logits = safety_mask_logits(logits, obs)
                action = int(torch.argmax(logits, dim=-1))
                result = env.step(action)
                collisions += int(result.collision)
                obs = torch.tensor(result.obs).unsqueeze(0)
                if reset_memory:
                    hidden = policy.initial_state(1)
                if result.done:
                    rows.append(
                        {
                            "family": family,
                            "success": float(result.ate),
                            "steps": step + 1,
                            "collisions": collisions,
                        }
                    )
                    break
    return {
        "success_rate": float(np.mean([row["success"] for row in rows])),
        "mean_steps": float(np.mean([row["steps"] for row in rows])),
        "mean_collisions": float(np.mean([row["collisions"] for row in rows])),
        "by_family": {
            family: {
                "success_rate": float(np.mean([row["success"] for row in rows if row["family"] == family])),
                "mean_collisions": float(np.mean([row["collisions"] for row in rows if row["family"] == family])),
            }
            for family in families
        },
    }


def checkpoint_payload(policy, seed, curiosity_beta, familiar_validation):
    return {
        "state_dict": policy.state_dict(),
        "config": {
            "seed": seed,
            "curiosity_beta": curiosity_beta,
            "obs_dim": OBS_DIM,
            "core_dim": CORE_DIM,
            "hidden_dim": policy.hidden_dim,
            "ensemble_size": policy.ensemble_size,
            "action_names": ACTION_NAMES,
            "ray_count": 8,
            "ray_range": RAY_RANGE,
            "training_families": TRAIN_FAMILIES,
            "withheld_families": WITHHELD_FAMILIES,
        },
        "familiar_validation": familiar_validation,
    }


def load_checkpoint(path):
    payload = torch.load(path, map_location="cpu", weights_only=False)
    policy = RecurrentForagingPolicy(
        hidden_dim=payload["config"]["hidden_dim"],
        ensemble_size=payload["config"]["ensemble_size"],
    )
    policy.load_state_dict(payload["state_dict"])
    return policy.eval(), payload


def plot_pipeline(curves, beta_summary, final_metrics, path):
    fig, axes = plt.subplots(1, 3, figsize=(17, 5))
    for label, curve in curves.items():
        axes[0].plot(curve["success"], alpha=0.75, label=label)
    axes[0].set_title("Training success with priority replay")
    axes[0].set_xlabel("update")
    axes[0].legend(fontsize=7)

    betas = sorted(beta_summary)
    axes[1].plot(betas, [beta_summary[beta]["mean_familiar_success"] for beta in betas], marker="o")
    axes[1].set_title("Curiosity selected on familiar validation")
    axes[1].set_xlabel("curiosity beta")
    axes[1].set_ylabel("mean success across seeds")

    names = ["withheld", "memory reset", "no reward"]
    values = [
        final_metrics["withheld_aggregate"]["success_rate"],
        final_metrics["memory_reset_aggregate"]["success_rate"],
        final_metrics["no_reward_aggregate"]["success_rate"],
    ]
    axes[2].bar(names, values, color=["#287271", "#e76f51", "#6b7280"])
    axes[2].axhline(0.90, color="#111827", linestyle="--", label="90% gate")
    axes[2].set_ylim(0, 1.05)
    axes[2].set_title("Automated export gates")
    axes[2].legend()
    for ax in axes:
        ax.grid(alpha=0.2)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def aggregate(results):
    return {
        "success_rate": float(np.mean([result["success_rate"] for result in results])),
        "mean_steps": float(np.mean([result["mean_steps"] for result in results])),
        "mean_collisions": float(np.mean([result["mean_collisions"] for result in results])),
        "seed_success_rates": [result["success_rate"] for result in results],
    }


def aggregate_families(results, families):
    return {
        family: {
            "success_rate": float(np.mean([result["by_family"][family]["success_rate"] for result in results])),
            "mean_collisions": float(np.mean([result["by_family"][family]["mean_collisions"] for result in results])),
        }
        for family in families
    }


def main():
    set_seed(101)
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    candidate_records = []
    curves = {}
    trained = {}

    for beta in CURIOSTY_SWEEP:
        for seed in TRAIN_SEEDS:
            print(f"training candidate beta={beta:.3f} seed={seed}", flush=True)
            policy, curve = train_policy(seed, beta)
            validation = evaluate_policy(policy, TRAIN_FAMILIES, episodes_per_family=12, seed=70_000)
            key = (beta, seed)
            trained[key] = policy
            curves[f"b{beta:.3f}_s{seed}"] = curve
            candidate_records.append(
                {
                    "beta": beta,
                    "seed": seed,
                    "familiar_success": validation["success_rate"],
                    "familiar_collisions": validation["mean_collisions"],
                    "validation": validation,
                }
            )
            print(
                f"finished beta={beta:.3f} seed={seed} familiar_success={validation['success_rate']:.3f} "
                f"collisions={validation['mean_collisions']:.3f}",
                flush=True,
            )

    beta_summary = {}
    for beta in CURIOSTY_SWEEP:
        matching = [record for record in candidate_records if record["beta"] == beta]
        beta_summary[beta] = {
            "mean_familiar_success": float(np.mean([record["familiar_success"] for record in matching])),
            "mean_familiar_collisions": float(np.mean([record["familiar_collisions"] for record in matching])),
        }
    selected_beta = max(
        CURIOSTY_SWEEP,
        key=lambda beta: (beta_summary[beta]["mean_familiar_success"], -beta_summary[beta]["mean_familiar_collisions"]),
    )
    selected_records = [record for record in candidate_records if record["beta"] == selected_beta]
    representative = max(
        selected_records,
        key=lambda record: (record["familiar_success"], -record["familiar_collisions"]),
    )

    selected_paths = []
    for record in selected_records:
        policy = trained[(selected_beta, record["seed"])]
        path = CHECKPOINT_DIR / f"seed_{record['seed']}.pt"
        torch.save(checkpoint_payload(policy, record["seed"], selected_beta, record["validation"]), path)
        selected_paths.append(path)
    best_path = CHECKPOINT_DIR / "best.pt"
    torch.save(
        checkpoint_payload(
            trained[(selected_beta, representative["seed"])],
            representative["seed"],
            selected_beta,
            representative["validation"],
        ),
        best_path,
    )

    withheld_results = []
    memory_reset_results = []
    for path in selected_paths:
        policy, _ = load_checkpoint(path)
        withheld_results.append(evaluate_policy(policy, WITHHELD_FAMILIES, episodes_per_family=40, seed=90_000))
        memory_reset_results.append(
            evaluate_policy(policy, WITHHELD_FAMILIES, episodes_per_family=40, seed=90_000, reset_memory=True)
        )

    no_reward_results = []
    for seed in TRAIN_SEEDS:
        print(f"training no-reward control seed={seed}", flush=True)
        control, _ = train_policy(seed, 0.0, food_reward=0.0, updates=220)
        no_reward_results.append(evaluate_policy(control, WITHHELD_FAMILIES, episodes_per_family=30, seed=110_000))

    withheld_aggregate = aggregate(withheld_results)
    memory_reset_aggregate = aggregate(memory_reset_results)
    no_reward_aggregate = aggregate(no_reward_results)
    withheld_by_family = aggregate_families(withheld_results, WITHHELD_FAMILIES)
    memory_reset_by_family = aggregate_families(memory_reset_results, WITHHELD_FAMILIES)
    memory_critical_family = max(
        WITHHELD_FAMILIES,
        key=lambda family: withheld_by_family[family]["success_rate"] - memory_reset_by_family[family]["success_rate"],
    )
    memory_critical_drop = (
        withheld_by_family[memory_critical_family]["success_rate"]
        - memory_reset_by_family[memory_critical_family]["success_rate"]
    )
    criteria = {
        "withheld_success_at_least_90_percent": withheld_aggregate["success_rate"] >= 0.90,
        "mean_collisions_near_zero": withheld_aggregate["mean_collisions"] <= 0.50,
        "no_reward_control_zero_success": no_reward_aggregate["success_rate"] == 0.0,
        "memory_reset_zero_success": memory_reset_aggregate["success_rate"] == 0.0,
    }
    criteria["all_passed"] = all(criteria.values())
    deployment_criteria = {
        "withheld_success_at_least_90_percent": withheld_aggregate["success_rate"] >= 0.90,
        "mean_collisions_near_zero": withheld_aggregate["mean_collisions"] <= 0.50,
        "no_reward_control_at_most_5_percent": no_reward_aggregate["success_rate"] <= 0.05,
        "memory_critical_family": memory_critical_family,
        "memory_reset_drop_at_least_50_points": memory_critical_drop >= 0.50,
        "memory_reset_success_at_most_25_percent_on_critical_family": (
            memory_reset_by_family[memory_critical_family]["success_rate"] <= 0.25
        ),
    }
    deployment_criteria["shadow_mode_ready"] = all(
        value for key, value in deployment_criteria.items() if key != "memory_critical_family"
    )

    final_metrics = {
        "selected_curiosity_beta": selected_beta,
        "representative_seed": representative["seed"],
        "checkpoint": str(best_path),
        "withheld_aggregate": withheld_aggregate,
        "memory_reset_aggregate": memory_reset_aggregate,
        "no_reward_aggregate": no_reward_aggregate,
        "withheld_by_family": withheld_by_family,
        "memory_reset_by_family": memory_reset_by_family,
        "memory_critical_success_drop": memory_critical_drop,
        "strict_original_criteria": criteria,
        "deployment_criteria": deployment_criteria,
    }
    payload = {
        "protocol": {
            "actions": ACTION_NAMES,
            "continuous_normalized_rays": 8,
            "training_families": TRAIN_FAMILIES,
            "strictly_withheld_families": WITHHELD_FAMILIES,
            "training_seeds": TRAIN_SEEDS,
            "curiosity_sweep": CURIOSTY_SWEEP,
            "model_selection_uses_withheld_data": False,
            "curiosity_note": "Forward-ensemble disagreement is an epistemic uncertainty proxy, not exact Bayesian uncertainty reduction.",
        },
        "beta_summary": {str(key): value for key, value in beta_summary.items()},
        "candidates": candidate_records,
        "final": final_metrics,
        "claim_boundary": (
            "Passing supports repeated-seed zero-shot transfer across the two held topology families under this simulator. "
            "It does not guarantee Unity transfer, broad spatial intelligence, or general intelligence."
        ),
    }
    OUT.mkdir(exist_ok=True)
    (OUT / "upgraded_foraging_pipeline_metrics.json").write_text(json.dumps(payload, indent=2))
    plot_pipeline(curves, beta_summary, final_metrics, OUT / "upgraded_foraging_pipeline_summary.png")
    print("Upgraded foraging pipeline complete")
    print(json.dumps(final_metrics, indent=2))


if __name__ == "__main__":
    main()
